title: peachessmasher
author: Sean Chang
email: lemoncoconut00@gmail.com
description: >-
  This is my first website that contains all of my past personal projects and achievemenets! I enjoy exploring different fields of computers-software development, web application,game
  design. I love learning things from other people that I don't know about. If you would like to contact me, please let me know by email!

social:
  twitter: seanchang
  facebook: seanchang
  instagram: seanchang
  github: seanchang
  linkedin: seanchang

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
