title: Multiverse by HTML5 UP
author: Sean Chang
email: lemoncoconut00@gmail.com
description: >-
  This is my first website that contains all of my past personal projects and achievemenets! I enjoy exploring different fields of computers-software development, web application,game
  design. I love learning things from other people that I don't know about. If there is anything I can do to improve the website, please let me know on the side!

social:
  twitter: seanchang
  facebook: seanchang
  instagram: seanchang
  github: seanchang
  linkedin: seanchang

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
